=== Schumann-IT/anypoint-api-cleanup/raml/api-manager-api-1.0.15-raml/apimanager/schemas/automatedPolicyPATCH.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-03/schema",
  "required": true,
  "properties": {
    "ruleOfApplication": {
      "type": "object",
      "required": true,
      "properties": {
        "organizationId": {
          "type": "string",
          "required": false,
          "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$",
          "examples": [
            "ba3dd49c-9bd3-43a3-bb54-226715e9c57a"
          ]
        },
        "environmentId": {
          "type": "string",
          "required": false,
          "minLength": 1,
          "examples": [
            "5d15a77c-0d35-400e-9a90-61d0beb09409"
          ]
        },
        "range": {
          "type": "object",
          "required": false,
          "properties": {
            "from": {
              "type": "string",
              "required": true,
              "examples": [
                "4.1.1"
              ]
            },
            "to": {
              "type": "string",
              "examples": [
                "4.1.1"
              ]
            }
          }
        }
      }
    },
    "groupId": {
      "type": "string",
      "maxLength": 256,
      "minLength": 1,
      "required": true
    },
    "assetId": {
      "type": "string",
      "maxLength": 256,
      "minLength": 1,
      "required": true
    },
    "assetVersion":{
      "type": "string",
      "maxLength": 256,
      "minLength": 1,
      "required": true
    },
    "configurationData": {
      "type": ["object", "array"],
      "required": true
    },
    "order": {
      "type": "integer",
      "minimum": 1
    },
    "disabled": {
      "type": "boolean"
    }
  }
}

=== Schumann-IT/anypoint-api-cleanup/raml/api-manager-api-1.0.15-raml/apimanager/examples/requests/automatedPolicy.json
{
  "ruleOfApplication": {
    "environmentId":        "5d15a77c-0d35-400e-9a90-61d0beb09409",
    "range": {
      "from": "4.1.1",
      "to":   "4.3.x"
    }
  },
  "groupId":          "68ef9520-24e9-4cf2-b2f5-620025690913",
  "assetId":          "rate-limiting",
  "assetVersion":     "1.0.0",
  "configurationData": {
    "rateLimits": [
      {
        "timePeriodInMilliseconds": 60000,
        "maximumRequests":          3
      }
    ],
    "clusterizable": true,
    "exposeHeaders": true
  }
}
