=== Schumann-IT/anypoint-api-cleanup/raml/api-manager-api-1.0.15-raml/apimanager/schemas/apiGroups/groupInstanceTierUpdate.json
{
  "type": "object",
  "$schema": "http://json-schema.org/draft-04/schema",
  "required": [
    "name",
    "status"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "minimum": 1
    },
    "groupVersionId": {
      "type": "integer",
      "minimum": 1
    },
    "name": {
      "type": "string",
      "maxLength": 256,
      "minLength": 1
    },
    "description":{
      "type": ["string", "null"],
      "maxLength": 256,
      "minLength": 1
    },
    "autoApprove": {
      "type": "boolean"
    },
    "status": {
      "type": "string",
      "enum": [
        "ACTIVE",
        "DEPRECATED"
      ]
    },
    "defaultLimits": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "maximumRequests",
          "timePeriodInMilliseconds",
          "visible"
        ],
        "properties": {
          "maximumRequests": {
            "type": "integer",
            "minimum": 1
          },
          "timePeriodInMilliseconds": {
            "type": "integer",
            "minimum": 1
          },
          "visible": {
            "type": "boolean"
          }
        }
      }
    },
    "limitsByApi": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "apiId",
          "limits"
        ],
        "properties":{
          "apiId": {
            "type": "integer",
            "minimum": 1
          },
          "limits": {
            "type": "array",
            "items": {
              "type": "object",
              "required": [
                "maximumRequests",
                "timePeriodInMilliseconds",
                "visible"
              ],
              "properties": {
                "maximumRequests": {
                  "type": "integer",
                  "minimum": 1
                },
                "timePeriodInMilliseconds": {
                  "type": "integer",
                  "minimum": 1
                },
                "visible": {
                  "type": "boolean"
                }
              }
            }
          }
        }
      }
    }
  }
}

=== Schumann-IT/anypoint-api-cleanup/raml/api-manager-api-1.0.15-raml/apimanager/examples/requests/apiGroups/groupInstanceTierCreation.json
{
  "status": "ACTIVE",
  "autoApprove": true,
  "limitsByApi": [
    {
      "apiId": 3,
      "limits": [
        {
            "visible": true,
            "maximumRequests": 5,
            "timePeriodInMilliseconds": 1
        }
      ]
    }
  ],
  "name": "tierName",
  "description": "tier description"
}
